[package]
name = "unitools-core"
version = "0.1.0"
edition = "2024"
authors = ["WangWindow"]
description = "工具箱应用的核心库"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
anyhow = "1.0"
dyn-clone = "1.0"
